# Generated by Django 2.2.1 on 2019-10-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=128, verbose_name='Автор')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=64, unique=True, verbose_name='Наименование категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128, verbose_name='Наименование продукта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, max_length=240, verbose_name='Краткое описание')),
                ('serial', models.TextField(blank=True, verbose_name='Серия')),
                ('language', models.TextField(blank=True, verbose_name='Язык издания')),
                ('type', models.TextField(blank=True, verbose_name='Тип')),
                ('issue_year', models.IntegerField(blank=True, verbose_name='Год выпуска')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Цена продукта')),
                ('balance', models.IntegerField(default=0, verbose_name='Остаток на складе')),
                ('product_image', models.ImageField(blank=True, upload_to='products_images')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Authors')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
        ),
    ]
